In [5]:
import torch

In [6]:
x = torch.tensor([ [1,2,3], [4,5,6], [7,8,9] ])

In [7]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
x.shape

torch.Size([3, 3])

In [9]:
x = torch.unsqueeze(x, 0)

In [10]:
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [11]:
x.shape

torch.Size([1, 3, 3])

In [12]:
x = torch.squeeze(x)

In [13]:
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [14]:
x.shape

torch.Size([3, 3])

In [15]:
x = x.view(9)

In [16]:
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
x.size()

torch.Size([9])

In [19]:
try:
    x = x.view(3,3)
except Exception as e:
    print(e)

In [20]:
x.size()

torch.Size([3, 3])

In [2]:
w = torch.randn(5, 3, dtype=torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])

In [3]:
print(w)

tensor([[ 0.8989,  0.5596, -0.6382],
        [-0.3290, -0.0308, -0.6124],
        [ 0.0282, -0.3825, -1.1386],
        [-0.0188,  1.6032,  1.0478],
        [ 0.2819, -1.1492,  2.2937]])


In [4]:
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [5]:
b = torch.randn(5,2, dtype=torch.float)
print(b)

tensor([[-0.4021,  0.2084],
        [-1.0243,  0.2699],
        [ 1.5295, -1.6171],
        [ 0.6099,  2.2401],
        [-0.9861, -0.1188]])


In [6]:
wx = torch.mm(w, x)

In [7]:
print("wx: ", wx)

wx:  tensor([[-0.6133,  0.2071],
        [-3.4834, -4.4555],
        [-6.8124, -8.3054],
        [10.0298, 12.6619],
        [ 8.3030,  9.7295]])


In [8]:
result = wx+b
print("result: ", result)

result:  tensor([[-1.0154,  0.4154],
        [-4.5077, -4.1857],
        [-5.2829, -9.9225],
        [10.6397, 14.9021],
        [ 7.3169,  9.6107]])
