### Convolution 2D

In [1]:
import numpy as np

In [7]:
X = np.array([[ 
                 [[1, 2, 9, 2, 7], 
                  [5, 0, 3, 1, 8], 
                  [4, 1, 3, 0, 6], 
                  [2, 5, 2, 9, 5], 
                  [6, 5, 1, 3, 2]], 
                 [[4, 5, 7, 0, 8], 
                  [5, 8, 5, 3, 5], 
                  [4, 2, 1, 6, 5], 
                  [7, 3, 2, 1, 0], 
                  [6, 1, 2, 2, 6]], 
                 [[3, 7, 4, 5, 0], 
                  [5, 4, 6, 8, 9], 
                  [6, 1, 9, 1, 6], 
                  [9, 3, 0, 2, 4], 
                  [1, 2, 5, 5, 2]] 
                 ], 
                [ 
                 [[7, 2, 1, 4, 2], 
                  [5, 4, 6, 5, 0], 
                  [1, 2, 4, 2, 8], 
                  [5, 9, 0, 5, 1], 
                  [7, 6, 2, 4, 6]], 
                 [[5, 4, 2, 5, 7], 
                  [6, 1, 4, 0, 5], 
                  [8, 9, 4, 7, 6], 
                  [4, 5, 5, 6, 7], 
                  [1, 2, 7, 4, 1]], 
                 [[7, 4, 8, 9, 7], 
                  [5, 5, 8, 1, 4], 
                  [3, 2, 2, 5, 2], 
                  [1, 0, 3, 7, 6], 
                  [4, 5, 4, 5, 5]] 
                 ] 
                ]) 
print('Images:', X.shape)

Images: (2, 3, 5, 5)


In [9]:
filters = np.array([[ 
                       [[1, 0, 1], 
                        [0, 1, 0], 
                        [1, 0, 1]], 
                       [[3, 1, 3], 
                        [1, 3, 1], 
                        [3, 1, 3]], 
                       [[1, 2, 1], 
                        [2, 2, 2], 
                        [1, 2, 1]] 
                       ],
                      [ 
                       [[5, 1, 5], 
                        [2, 1, 2], 
                        [5, 1, 5]], 
                       [[1, 1, 1], 
                        [1, 1, 1], 
                        [1, 1, 1]], 
                       [[2, 0, 2], 
                        [0, 2, 0], 
                        [2, 0, 2]], 
                       ], 
                      [ 
                       [[5, 1, 5], 
                        [2, 1, 2], 
                        [5, 1, 5]],
                       [[1, 1, 1], 
                        [1, 1, 1], 
                        [1, 1, 1]], 
                       [[2, 0, 2], 
                        [0, 2, 0], 
                        [2, 0, 2]], 
                       ] 
                      ]) 
print('Filters:', filters.shape)

Filters: (3, 3, 3, 3)


In [25]:
def conv2D(X, filters, stride=1, padding=0):
  n, channel, height, width = X.shape
  n_f, c_f, h_f, w_f = filters.shape

  out_height = (height + padding * 2 - h_f) // stride + 1
  out_width = (width + padding * 2 - w_f) // stride + 1
  out = np.zeros([n, n_f, out_height, out_width])

  X_pad = np.pad(X, pad_width=padding, mode='constant', constant_values=0)

  for batch in range(n):  # 이미지 수
    for c in range(n_f):  # 채널
      for h in range(out_height):  # 높이
        h_start = h * stride
        h_end = h_start + h_f
        for w in range(out_width): # 너비
          w_start = w * stride
          w_end = w_start + w_f

          out[batch, c, h, w] = np.sum(X_pad[batch, :, h_start:h_end, w_start:w_end] * filters[c])

  return out

In [26]:
out = conv2D(X, filters, stride=2, padding=0)
print(out)
print(out.shape)

[[[[174. 191.]
   [130. 122.]]

  [[197. 244.]
   [165. 159.]]

  [[197. 244.]
   [165. 159.]]]


 [[[168. 171.]
   [153. 185.]]

  [[188. 178.]
   [168. 200.]]

  [[188. 178.]
   [168. 200.]]]]
(2, 3, 2, 2)
