### Instance Normalization

In [ ]:
import numpy
# import torch

In [ ]:
X = np.array([[ 
                 [[1, 2, 9, 2, 7], 
                  [5, 0, 3, 1, 8], 
                  [4, 1, 3, 0, 6], 
                  [2, 5, 2, 9, 5], 
                  [6, 5, 1, 3, 2]], 
                 [[4, 5, 7, 0, 8], 
                  [5, 8, 5, 3, 5], 
                  [4, 2, 1, 6, 5], 
                  [7, 3, 2, 1, 0], 
                  [6, 1, 2, 2, 6]], 
                 [[3, 7, 4, 5, 0], 
                  [5, 4, 6, 8, 9], 
                  [6, 1, 9, 1, 6], 
                  [9, 3, 0, 2, 4], 
                  [1, 2, 5, 5, 2]] 
                 ], 
                [ 
                 [[7, 2, 1, 4, 2], 
                  [5, 4, 6, 5, 0], 
                  [1, 2, 4, 2, 8], 
                  [5, 9, 0, 5, 1], 
                  [7, 6, 2, 4, 6]], 
                 [[5, 4, 2, 5, 7], 
                  [6, 1, 4, 0, 5], 
                  [8, 9, 4, 7, 6], 
                  [4, 5, 5, 6, 7], 
                  [1, 2, 7, 4, 1]], 
                 [[7, 4, 8, 9, 7], 
                  [5, 5, 8, 1, 4], 
                  [3, 2, 2, 5, 2], 
                  [1, 0, 3, 7, 6], 
                  [4, 5, 4, 5, 5]] 
                 ] 
                ]) 
print(X.shape)

(2, 3, 5, 5)

In [ ]:
n, c, h, w = X.shape

In [ ]:
# 평균
X_mean = np.mean(X.reshape(n, c, -1), axis=2).reshape(n, c, 1, 1)
print(X_mean)
print(X_mean.shape)

### PyTorch
# X_mean = X.view(n, c, -1).mean(dim=2).view(n, c, 1, 1)

[[[[3.68]]

  [[3.92]]

  [[4.28]]]


 [[[3.92]]

  [[4.6 ]]

  [[4.48]]]]
(2, 3, 1, 1)


In [ ]:
# 분산, 표준편차
eps = 1e-5
X_var = np.var(X.reshape(n, c, -1), axis=2) + eps
X_std = np.sqrt(X_var).reshape(n, c, 1, 1)
print(X_std)
print(X_std.shape)

### PyTorch
# X_var = X.view(n, c, -1).var(dim=2) + eps
# X_std = X_var.sqrt().view(n, c, 1, 1)

[[[[2.6490772 ]]

  [[2.39866838]]

  [[2.73525319]]]


 [[[2.48064709]]

  [[2.3323829 ]]

  [[2.33443998]]]]
(2, 3, 1, 1)


In [ ]:
# Instance Normalization
output = (X - X_mean) / X_std
print(output)
print(output.shape)

[[[[-1.01167305 -0.6341831   2.0082465  -0.6341831   1.25326661]
   [ 0.49828672 -1.38916299 -0.25669316 -1.01167305  1.63075655]
   [ 0.12079678 -1.01167305 -0.25669316 -1.38916299  0.87577667]
   [-0.6341831   0.49828672 -0.6341831   2.0082465   0.49828672]
   [ 0.87577667  0.49828672 -1.01167305 -0.25669316 -0.6341831 ]]

  [[ 0.03335184  0.45024982  1.28404578 -1.63424008  1.70094375]
   [ 0.45024982  1.70094375  0.45024982 -0.38354614  0.45024982]
   [ 0.03335184 -0.80044412 -1.2173421   0.8671478   0.45024982]
   [ 1.28404578 -0.38354614 -0.80044412 -1.2173421  -1.63424008]
   [ 0.8671478  -1.2173421  -0.80044412 -0.80044412  0.8671478 ]]

  [[-0.46796399  0.99442348 -0.10236712  0.26322975 -1.5647546 ]
   [ 0.26322975 -0.10236712  0.62882661  1.36002035  1.72561722]
   [ 0.62882661 -1.19915773  1.72561722 -1.19915773  0.62882661]
   [ 1.72561722 -0.46796399 -1.5647546  -0.83356086 -0.10236712]
   [-1.19915773 -0.83356086  0.26322975  0.26322975 -0.83356086]]]


 [[[ 1.24161152 -