In [24]:
import numpy as np

In [99]:
x_train = np.array([[10, 25, 15],
                    [20, 30, 25],
                    [70, 75, 90],
                    [90, 80, 100]])
y_train = np.array([0, 0, 1, 1])

print(x_train.shape)
print(y_train.shape)

(4, 3)
(4,)


In [100]:
use_bias = False

In [101]:
if use_bias:
  b = np.ones((x_train.shape[0], 1))
  x_train = np.concatenate((b, x_train), axis=1)
  print(x_train)

In [102]:
W = np.random.rand(x_train.shape[1])
print(W)

[0.56333908 0.65361235 0.14310761]


In [103]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [104]:
n = len(y_train)

epochs = 10000
learning_rate = 0.01

In [105]:
for epoch in range(epochs):
  hypothesis = sigmoid(np.dot(x_train, W)) # (4,1)
  cost = -(y_train * np.log(hypothesis) + (1 - y_train) * np.log(1 - hypothesis)).mean()

  # 파라미터 update
  gradient_W = np.dot(x_train.transpose(), hypothesis - y_train) / n # (3,1)
  W = W - gradient_W * learning_rate  # (3,1)

  if (epoch + 1) % 500 == 0:
    print('Epoch {:5d}  cost: {:10f}'.format(epoch + 1, cost))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in multiply
  This is separate from the ipykernel package so we can avoid doing imports until


Epoch   500  cost:   0.005655
Epoch  1000  cost:   0.002951
Epoch  1500  cost:   0.001997
Epoch  2000  cost:   0.001509
Epoch  2500  cost:   0.001213
Epoch  3000  cost:   0.001014
Epoch  3500  cost:   0.000871
Epoch  4000  cost:   0.000764
Epoch  4500  cost:   0.000680
Epoch  5000  cost:   0.000612
Epoch  5500  cost:   0.000557
Epoch  6000  cost:   0.000511
Epoch  6500  cost:   0.000472
Epoch  7000  cost:   0.000439
Epoch  7500  cost:   0.000410
Epoch  8000  cost:   0.000384
Epoch  8500  cost:   0.000362
Epoch  9000  cost:   0.000342
Epoch  9500  cost:   0.000324
Epoch 10000  cost:   0.000308


In [106]:
print(W)

[ 0.77402833 -1.05419285  0.36668913]


In [107]:
x_test = np.array([[99, 90, 87],
                   [20, 40, 25],
                   [30, 40, 15],
                   [70, 81, 89]])

if use_bias:
  b = np.ones((x_test.shape[0], 1))
  x_test = np.concatenate((b, x_test), axis=1)
answer = sigmoid(np.dot(x_test, W))
print(answer)
print(answer.round())

[9.99998824e-01 2.46147712e-08 1.44626151e-06 8.06541928e-01]
[1. 0. 0. 1.]


참고

https://yamalab.tistory.com/79

https://pythonkim.tistory.com/18